# docker-compose.yml
services:
  db:
    image: postgres:15
    container_name: property-db
    environment:
      - POSTGRES_DB=propertydb
      - POSTGRES_USER=propertyuser
      - POSTGRES_PASSWORD=propertypass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .  
    container_name: property-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app  
      - ./media:/app/media   
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://propertyuser:propertypass@db:5432/propertydb

volumes:
  postgres_data: